custom_stopwords = {
        # english
    'game', 'football', 'manager', 'fm', 'fm26', 'play', 'player', 'players',
    'year', 'like', 'still', 'bad', 'worst', 'awful', 'ever', 'terrible', 'good',
    'just', 'get', 'even', 'one', 'much', 'really', 'make', 'time', 'would',
    'buy', 'bought', 'version', 'sports', 'interactive', 'also', 'know', 'go',
    'could', 'say', 'thing', 'way', 'think', 'see', 'every', 'many', 'want', 'take',
    'se','manager','dont','ive','better','back','version','feel','please','keep','cant',
    'lot','full','absolutely','compared','years','year','keep','keeps',
    'played','team','teams', 'step','steps','made','total','love','killed','kill', 
    'playing','match','matchs','matches',
    'ability', 'able', 'absolute', 'actual', 'actually', 'add', 'added', 
    'adding', 'addition', 'ago', 'almost', 'already', 'always', 'amazing', 'annoying', 
    'another', 'anymore', 'anyone', 'anything', 'anyway', 'around', 'asking', 'aspect', 
    'attempt', 'away', 'backwards', 'barely', 'basic', 'basically', 'become', 'behind', 
    'believe', 'best', 'big', 'biggest', 'bit', 'bother', 'boy', 'break', 'bring', 
    'build', 'button', 'buying', 'came', 'care', 'case', 'certain', 'chance', 'change', 
    'changed', 'check', 'choice', 'choose', 'chore', 'clear', 'clearly', 'click', 
    'clicking', 'close', 'come', 'coming', 'community', 'company', 'competition', 
    'complete', 'completely', 'confusing', 'considering', 'constant', 'constantly', 
    'continue', 'core', 'couldnt', 'crap', 'crazy', 'create', 'created', 'current', 
    'cut', 'data', 'day', 'decade', 'decent', 'decided', 'decision', 'definitely', 
    'designed', 'despite', 'detail', 'development', 'didnt', 'different', 'difficult', 
    'direction', 'disappointed', 'disappointing', 'disappointment', 'disaster', 
    'discount', 'disgrace', 'doesnt', 'done', 'drop', 'due', 'earlier', 'early', 
    'easily', 'easy', 'edition', 'either', 'element', 'else', 'end', 'enjoy', 
    'enjoyable', 'enjoyed', 'enough', 'entire', 'especially', 'etc', 'everyone', 
    'everything', 'everywhere', 'exactly', 'example', 'expect', 'expected', 'expecting', 
    'experience', 'extra', 'extremely', 'eye', 'fact', 'fan', 'far', 'february', 
    'feedback', 'feeling', 'felt', 'finally', 'find', 'finding', 'finished', 'first', 
    'flow', 'focus', 'forward', 'found', 'free', 'friendly', 'frustrating', 'fully', 
    'fun', 'function', 'future', 'gameplay', 'gaming', 'garbage', 'gave', 'genuinely', 
    'getting', 'give', 'given', 'giving', 'god', 'going', 'gone', 'got', 'great', 
    'guess', 'guy', 'half', 'hard', 'harder', 'hasnt', 'hate', 'havent', 'head', 'hell', 
    'help', 'hidden', 'history', 'honest', 'honestly', 'hope', 'hopefully', 'hoping', 
    'horrendous', 'horrible', 'hour', 'however', 'huge', 'hundred', 'id', 'idea', 'ill', 
    'im', 'imagine', 'immersion', 'immersive', 'important', 'impossible', 'improved', 
    'improvement', 'incredibly', 'info', 'information', 'ingame', 'instead', 
    'interaction', 'interesting', 'intuitive', 'isnt', 'issue', 'itch', 'iteration', 
    'job', 'joke', 'kept', 'key', 'kick', 'lack', 'last', 'later', 'launch', 'least', 
    'left', 'less', 'let', 'level', 'life', 'line', 'list', 'literally', 'little', 
    'long', 'longer', 'look', 'looking', 'lose', 'losing', 'lost', 'loved', 'main', 
    'major', 'majority', 'making', 'man', 'manage', 'managed', 'management', 'managing', 
    'massive', 'matter', 'may', 'maybe', 'mean', 'mention', 'mess', 'message', 'might', 
    'mile', 'min', 'mind', 'minute', 'missing', 'mistake', 'money', 'month', 'multiple', 
    'must', 'name', 'national', 'navigate', 'navigating', 'near', 'nearly', 'need', 
    'needed', 'negative', 'never', 'new', 'next', 'nice', 'nothing', 'number', 'offer', 
    'often', 'oh', 'ok', 'old', 'older', 'open', 'opinion', 'opposition', 'option', 
    'others', 'otherwise', 'outside', 'overall', 'page', 'paid', 'part', 'past', 
    'people', 'piece', 'pile', 'place', 'playable', 'plus', 'point', 'polished', 'poor', 
    'poorly', 'position', 'positive', 'possession', 'possible', 'preordered', 'press', 
    'pretty', 'previous', 'previously', 'probably', 'problem', 'product', 'promised', 
    'proper', 'properly', 'purchase', 'put', 'quality', 'quickly', 'quite', 'randomly', 
    'rather', 'read', 'real', 'reality', 'reason', 'recent', 'recommend', 'recommended', 
    'remove', 'removed', 'removing', 'report', 'result', 'review', 'right', 'role', 
    'rubbish', 'ruined', 'run', 'sad', 'sadly', 'said', 'sale', 'save', 'saying', 
    'score', 'scratch', 'search', 'second', 'section', 'seeing', 'seem', 'seems', 
    'seen', 'sense', 'series', 'set', 'setting', 'setup', 'several', 'shame', 'shocking', 
    'shot', 'shouldnt', 'show', 'showing', 'simple', 'simply', 'since', 'single', 
    'skip', 'slow', 'small', 'smooth', 'somehow', 'someone', 'something', 'sometimes', 
    'space', 'spend', 'spent', 'standard', 'start', 'started', 'state', 'stick', 'stop', 
    'straight', 'stuff', 'stupid', 'sub', 'suck', 'sure', 'system', 'taken', 'tell', 
    'term', 'test', 'text', 'th', 'thanks', 'thats', 'there', 'theyre', 'theyve', 
    'thinking', 'though', 'thought', 'thousand', 'tiny', 'title', 'took', 'top', 
    'totally', 'trash', 'tried', 'TRUE', 'try', 'trying', 'turn', 'two', 'ugly', 
    'understand', 'unfinished', 'unfortunately', 'unintuitive', 'unplayable', 
    'unpolished', 'use', 'used', 'useless', 'user', 'using', 'veteran', 'view', 'wait', 
    'waited', 'waiting', 'wanted', 'wasnt', 'waste', 'watch', 'watching', 'well', 
    'went', 'whatever', 'whats', 'whether', 'whilst', 'whole', 'wish', 'without', 
    'wont', 'word', 'work', 'working', 'world', 'worse', 'worth', 'wouldnt', 'wouldve', 
    'writing', 'wrong', 'yes', 'yet', 'youd', 'youre', 'youve',
    'abomination', 'abysmal', 'accept', 'acceptable', 'accessible', 'account', 'across', 
    'act', 'action', 'actively', 'addict', 'addicted', 'addiction', 'addictive', 
    'additional', 'address', 'adjust', 'advanced', 'advice', 'advise', 'afraid', 'age', 
    'agent', 'agree', 'ahead', 'aint', 'allow', 'allowed', 'allowing', 'alone', 'along', 
    'alot', 'alpha', 'although', 'amount', 'analysis', 'angle', 'angry', 'announced', 
    'answer', 'anywhere', 'apart', 'appalling', 'apparently', 'appeal', 'appear', 
    'appears', 'application', 'appreciate', 'approach', 'area', 'arent', 'arrow', 
    'ashamed', 'aside', 'ask', 'asked', 'assistant', 'atrocious', 'attacking', 
    'attention', 'attribute', 'audience', 'available', 'average', 'avoid', 'awkward', 
    'background', 'backward', 'badly', 'baffling', 'balance', 'bar', 'bare', 'base', 
    'based', 'beautiful', 'became', 'becomes', 'begin', 'beginning', 'benefit', 
    'besides', 'beyond', 'bigger', 'bizarre', 'black', 'blank', 'board', 'bookmark', 
    'borderline', 'boring', 'bothered', 'bottom', 'box', 'brand', 'breaking', 'bright', 
    'brilliant', 'brings', 'broke', 'broken', 'brought', 'budget', 'building', 'built', 
    'bunch', 'buried', 'business', 'calendar', 'call', 'called', 'cancellation', 
    'cancelled', 'card', 'cash', 'casual', 'cause', 'centre', 'certainly', 'challenge', 
    'champ', 'champion', 'championship', 'changing', 'character', 'charge', 'charging', 
    'cheap', 'chose', 'classic', 'clean', 'clicked', 'club', 'clunky', 'cluttered', 
    'color', 'colour', 'column', 'comment', 'common', 'communication', 'compare', 
    'comparing', 'comparison', 'competitor', 'complaint', 'complex', 'complicated', 
    'computer', 'con', 'conclusion', 'condition', 'conference', 'consider', 'considered', 
    'content', 'control', 'controller', 'cool', 'copy', 'corner', 'correct', 'correctly', 
    'cost', 'countless', 'couple', 'course', 'creating', 'creation', 'creator', 
    'critical', 'criticism', 'cross', 'crowd', 'cumbersome', 'cup', 'currently', 
    'custom', 'customer', 'customisation', 'customization', 'customize', 'cycle', 
    'damn', 'date', 'de', 'dead', 'deadline', 'deal', 'decide', 'deck', 'dedicated', 
    'deep', 'deeper', 'deeply', 'default', 'delayed', 'delegate', 'deliver', 'delivered', 
    'demand', 'demo', 'depth', 'describe', 'deserve', 'design', 'designer', 
    'desperately', 'destroyed', 'detailed', 'dev', 'develop', 'developed', 'developer', 
    'developing', 'devs', 'die', 'difference', 'disconnected', 'disgusting', 'dislike', 
    'display', 'displayed', 'dissapointed', 'doe', 'double', 'doubt', 'downgrade', 
    'download', 'dozen', 'drag', 'draw', 'dreadful', 'dribble', 'dribbling', 'dropped', 
    'dumb', 'dumbed', 'dynamic', 'earned', 'earth', 'easier', 'edit', 'effectively', 
    'effort', 'eg', 'email', 'embarrassing', 'empty', 'encountered', 'ended', 'endless', 
    'engaging', 'enjoying', 'enjoyment', 'entirely', 'entry', 'era', 'error', 'essential', 
    'essentially', 'euro', 'eventually', 'evolution', 'exact', 'excel', 'excellent', 
    'except', 'excited', 'excuse', 'execution', 'exist', 'existing', 'expectation', 
    'experienced', 'face', 'fail', 'failed', 'fails', 'failure', 'fair', 'faith', 
    'fall', 'familiar', 'fanbase', 'fantastic', 'fast', 'faster', 'favorite', 'favourite', 
    'fear', 'feature', 'fewer', 'figure', 'file', 'filled', 'filter', 'final', 'finance', 
    'fine', 'finger', 'finish', 'fire', 'fired', 'fit', 'five', 'fix', 'fixed', 'fixing', 
    'fixture', 'flaw', 'fmcm', 'focused', 'follow', 'following', 'font', 'foot', 'force', 
    'forced', 'forcing', 'forever', 'forget', 'forgot', 'form', 'formation', 'forum', 
    'foundation', 'four', 'franchise', 'frankly', 'fresh', 'friend', 'frustrated', 
    'frustration', 'fullback', 'functional', 'functionality', 'fundamental', 
    'fundamentally', 'gamebreaking', 'gamers', 'general', 'generally', 'generation', 
    'glance', 'gon', 'gotten', 'grab', 'graph', 'graphical', 'graphically', 'ground', 
    'gutted', 'halfbaked', 'hand', 'handle', 'happen', 'happened', 'happening', 
    'happens', 'happy', 'hardcore', 'headache', 'heart', 'heat', 'heatmaps', 'heavily', 
    'heavy', 'hey', 'hide', 'high', 'higher', 'highlight', 'hire', 'hit', 'hold', 
    'holding', 'home', 'hoped', 'horrific', 'hot', 'hr', 'hub', 'hurt', 'hype', 'icon', 
    'idiot', 'ignore', 'ignored', 'ignoring', 'immediately', 'immersed', 'imo', 'impact', 
    'implement', 'implementation', 'implemented', 'impressive', 'improve', 'improving', 
    'inbox', 'including', 'incomplete', 'inconsistent', 'increase', 'incredible', 
    'individual', 'infuriating', 'injured', 'inmatch', 'innovation', 'inout', 'insane', 
    'inside', 'installment', 'instance', 'instant', 'instruction', 'insult', 'intended', 
    'interest', 'interested', 'international', 'interview', 'involved', 'ip', 'item', 
    'itll', 'jacobson', 'january', 'joy', 'jump', 'keyboard', 'kid', 'kind', 'kinda', 
    'kit', 'knew', 'knowing', 'known', 'la', 'lacking', 'laptop', 'large', 'late', 
    'latest', 'launched', 'layer', 'lazy', 'lead', 'leaf', 'leap', 'learn', 'learning', 
    'leave', 'leaving', 'legacy', 'letdown', 'license', 'liked', 'likely', 'limited', 
    'lineup', 'link', 'listen', 'live', 'loaded', 'loading', 'loan', 'lock', 'locked', 
    'logic', 'lol', 'longterm', 'longtime', 'looked', 'loss', 'low', 'lower', 'loyal', 
    'luck', 'magic', 'manually', 'map', 'mark', 'market', 'marketing', 'massively', 
    'meaning', 'meaningful', 'meant', 'mechanic', 'medium', 'meet', 'meeting', 'member', 
    'memory', 'men', 'mentioned', 'messed', 'messy', 'mid', 'middle', 'million', 
    'minimal', 'minimum', 'minor', 'miss', 'missed', 'mixed', 'mobile', 'modders', 
    'mode', 'model', 'modern', 'moment', 'monitor', 'mostly', 'mouse', 'move', 'moved', 
    'movement', 'moving', 'na', 'nd', 'necessary', 'negotiation', 'neither', 'news', 
    'nicer', 'nightmare', 'nobody', 'non', 'none', 'nonsense', 'nope', 'normal', 
    'normally', 'note', 'notice', 'november', 'nowhere', 'numerous', 'objectively', 
    'obvious', 'obviously', 'official', 'okay', 'onto', 'oop', 'opponent', 'opportunity', 
    'opposite', 'order', 'original', 'overhaul', 'overly', 'overview', 'pain', 'painful', 
    'painfully', 'paint', 'panel', 'para', 'particularly', 'pas', 'pass', 'passing', 
    'patched', 'pathetic', 'patience', 'pay', 'paying', 'pc', 'per', 'perfect', 
    'perfectly', 'perhaps', 'period', 'person', 'personal', 'personally', 'phase', 
    'phone', 'pick', 'plain', 'plan', 'platform', 'playerbase', 'plenty', 'pointless', 
    'polish', 'pop', 'popup', 'popups', 'port', 'possibly', 'post', 'potential', 'pre', 
    'prefer', 'preference', 'pregame', 'premier', 'present', 'presentation', 'presented', 
    'pressing', 'price', 'prior', 'priority', 'pro', 'process', 'produce', 'profile', 
    'progress', 'project', 'promise', 'promising', 'public', 'pull', 'purchased', 
    'purchasing', 'pure', 'purpose', 'push', 'pushed', 'putting', 'qa', 'qol', 'que', 
    'question', 'quick', 'quit', 'random', 'rating', 'reach', 'reading', 'ready', 
    'realise', 'realism', 'realistic', 'received', 'recommendation', 'record', 
    'recruitment', 'red', 'reduced', 'refund', 'refunded', 'refunding', 'refuse', 
    'regardless', 'register', 'regression', 'regret', 'regular', 'regularly', 'release', 
    'released', 'releasing', 'relevant', 'remain', 'remains', 'remember', 'removal', 
    'repeat', 'repetitive', 'replaced', 'replay', 'reported', 'reputation', 'request', 
    'requested', 'require', 'required', 'requires', 'reserve', 'respect', 'response', 
    'responsibility', 'rest', 'restart', 'return', 'revert', 'rid', 'riddled', 
    'ridiculous', 'rip', 'room', 'rough', 'round', 'row', 'ruin', 'rule', 'running', 
    'rushed', 'sake', 'salary', 'saved', 'saving', 'saw', 'scale', 'scaling', 'scam', 
    'schedule', 'scored', 'scroll', 'scrolling', 'searching', 'seemingly', 'sega', 
    'select', 'selection', 'self', 'sell', 'selling', 'separate', 'serious', 'seriously', 
    'session', 'severely', 'shallow', 'shamble', 'shape', 'sheer', 'shift', 'short', 
    'shortcut', 'shortlist', 'shouldve', 'shout', 'shown', 'sht', 'side', 'sign', 
    'signed', 'significant', 'significantly', 'silly', 'similar', 'simplified', 'sit', 
    'situation', 'size', 'skipped', 'skipping', 'slap', 'slightly', 'slower', 'sluggish', 
    'smaller', 'smoother', 'soccer', 'software', 'sold', 'solid', 'somewhat', 
    'somewhere', 'soon', 'sorry', 'sort', 'sorted', 'soul', 'soulless', 'sound', 
    'spacebar', 'special', 'specific', 'spending', 'sport', 'spreadsheet', 'squad', 
    'st', 'staff', 'stage', 'stand', 'standing', 'star', 'starting', 'statistic', 
    'stay', 'steam', 'sticking', 'stopped', 'story', 'strange', 'stripped', 'struggle', 
    'struggling', 'stuck', 'studio', 'style', 'submenu', 'substitution', 'success', 
    'suddenly', 'suggest', 'summary', 'super', 'support', 'supported', 'supposed', 
    'surely', 'switch', 'switching', 'tab', 'table', 'tablet', 'tag', 'taker', 'taking', 
    'talk', 'talking', 'target', 'task', 'tbh', 'technical', 'tedious', 'telling', 'ten', 
    'terribly', 'tested', 'tester', 'testing', 'thank', 'theyll', 'third', 'three', 
    'throughout', 'throw', 'thrown', 'thumb', 'tile', 'till', 'tldr', 'today', 
    'together', 'told', 'ton', 'tool', 'touch', 'touchline', 'towards', 'track', 
    'transition', 'TRUE', 'truly', 'trust', 'turned', 'tweak', 'twice', 'type', 
    'ultimately', 'unable', 'unacceptable', 'unbelievable', 'uninstalled', 'unless', 
    'unnecessarily', 'unnecessary', 'unread', 'unrealistic', 'unresponsive', 'unusable', 
    'updated', 'upgrade', 'upgraded', 'upon', 'ups', 'usability', 'useful', 'usual', 
    'usually', 'utter', 'utterly', 'value', 'various', 'verdict', 'via', 'video', 
    'vision', 'visual', 'visually', 'visuals', 'wa', 'wage', 'wan', 'wanting', 'wasted', 
    'wasting', 'watermark', 'week', 'weird', 'welcome', 'weve', 'whenever', 'whoever', 
    'wide', 'willing', 'win', 'window', 'winning', 'within', 'woke', 'woman', 'womens', 
    'wonder', 'worked', 'wow', 'write', 'wtf', 'xi', 'yeah', 'yearly', 'youll', 'zero',
    'ha', 'si', 'beta', 'league', 'cm',
    'lu', 'worked', 'wow', 'write', 'wtf', 'xi', 'yeah', 'yearly', 'youll', 'zero',

    # Bahasa Indonesia
    "bakso", "ga", "suka", "tidak", "sama", "yang", "ume", "sangat", "dengan", "dgn", 
    "yg", "dgn", "dr", "dlm", "kpd", "tsb", "pdhl", "krn", "karna", "karna", 
    "yg", "dgn", "dr", "dlm", "kpd", "tsb", "pdhl", "krn", "karna", "karna", 

    "yg", "dgn", "dr", "dlm", "kpd", "tsb", "pdhl", "krn", "karna", "karna", 
    "tp", "tapi", "bgt", "banget", "kyk", "kayak", "dkk", "bsk", "kmrn", 
    "bnyk", "sbb", "dll", "ttg", "tentang", "gitu", "begitu", "gini", "begini", 
    "dapet", "dapat", "trus", "terus", "lg", "lagi", "pas", "sbg", "drpd", 
    "kpn", "gmn", "gimana", "gmana", "gpp", "gapapa", "bkn", "bukan", "ntar", 
    "entar", "mo", "mau", "mw", "dlu", "dulu", "kl", "klo", "kalo", "kalau", 
    "dnk", "donk", "dong", "bener", "beneran", "bet", "bat", "udh", "udah", 
    "sudah", "cmn", "cuman", "cuma", "aja", "saja", "doang", "jd", "jadi", 
    "skrg", "skrng", "sekarang", "krna", "emng", "emang", "memang", "jg", "juga",
    "gw", "gua", "gue", "aku", "saya", "ane", "abdi", "lu", "elo", "elu", 
    "kamu", "anda", "ente", "kita", "kami", "dia", "mereka", "nya", "mu", "ku", 
    "sih", "tuh", "deh", "mah", "teh", "kok", "kek", "kan", "nah", "lho", "loh", 
    "yah", "ya", "wae", "atuh", "euy", "dong", "pun", "kang", "bang", "kak", 
    "min", "mimin", "gan", "agan",
    "bagus", "keren", "mantap", "mantul", "jelek", "buruk", "parah", "hancur", 
    "payah", "lumayan", "biasa", "mending", "kece", "bosen", "membosankan", 
    "garing", "males", "malesin", "seru", "asik", "asyik", "nagih", "oke", 
    "ok", "sip", "joss", "gg", "gila", "anjay", "anjir", "njir", "hebat",
    "sukses", "gagal", "kecewa", "puas", "mantap", "nyaman", "anjay", "keren",
    "main", "mainin", "mainnya", "bermain", "bikin", "buat", "ada", "adalah", 
    "kasih", "ngasih", "minta", "cari", "nyari", "lihat", "liat", "dengar", 
    "denger", "bilang", "ngomong", "rasa", "ngerasa", "tau", "tahu", "ngerti", 
    "paham", "selesai", "mulai", "jalan", "masuk", "keluar", "pakai", "pake", 
    "harap", "moga", "semoga", "tunggu", "nunggu", "coba", "nyoba", "beli", 
    "jual", "tambah", "kurang", "bantu", "tolong",
    "jam", "menit", "detik", "hari", "minggu", "bulan", "tahun", "besok", 
    "kemarin", "tadi", "nanti", "pagi", "siang", "sore", "malam", "selalu", 
    "pernah", "sering", "jarang", "kadang", "banyak", "sedikit", "dikit", 
    "semua", "tiap", "setiap", "ini", "itu", "sini", "situ", "sana", "masih", 
    "belum", "awal", "akhir", "baru", "lama", "sekarang", "kedepan", "lalu",
    "pertama", "kedua", "ketiga", "kali", "sekali", "sebentar",
    "haha", "hahaha", "hehe", "hehehe", "wkwk", "wkwkwk", "wkwkwkwk", "xixi", 
    "xixixi", "awok", "awokawok", "ckck", "hmm", "hmmm", "wah", "wow", "wuih", 
    "ooo", "oh", "astaga", "aduh", "yey", "wkkwkw", "muehehe", "ah", "ih", "eh",
    "dan", "atau", "tetapi", "namun", "melainkan", "sedangkan", "serta", 
    "karena", "sebab", "sehingga", "maka", "agar", "supaya", "untuk", "bagi", 
    "dari", "ke", "di", "pada", "dalam", "yaitu", "yakni", "adalah", "ialah", 
    "bahwa", "seperti", "sebagai", "bisa", "dapat", "mampu", "harus", "wajib", 
    "akan", "telah", "sedang", "bahkan", "jika", "kalau", "apabila", "walau", 
    "meski"
}

